# -*- coding: utf-8 -*-
"""Programming_Assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18u7jWmLG7sVXGzJVhur4TDr18qstQCZC
"""

#Write a Python Program to Check if a Number is Positive, Negative or Zero?

Num = int(input('Enter the number '))



if Num>0:
  print(('positive'))
elif Num<0:
  print('Negative')
else:
  print('Zero')

#Write a Python Program to Check if a Number is Odd or Even?

Num = int(input('Enter the number '))



if Num%2 ==0:
  print(('Even'))
elif Num%2!=0:
  print('Odd')

#Write a Python Program to Check Leap Year?

Num = int(input('Enter the number '))



if Num%4 ==0:
  print(('Leap year'))
elif Num%4!=0:
  print('Not a leap year')

#Write a Python Program to Check Prime Number?
Num = int(input('Enter the number '))
Factor =[]
for i in range(2, Num):

  if Num%i ==0:
    Factor.append(Num%i)
    
if len(Factor)>0:
  print('It is not a prime number')

else:
  print('It is a prime number')

#Write a Python Program to Print all Prime Numbers in an Interval of 1-10000?

prime_numbers = []
#Factor =[]
for i in range(2,10001):
  Factor=[]
  for j in range(2, i):

    if i%j ==0:
      Factor.append(i%j)
    
  if len(Factor)==0:
    prime_numbers.append(i)
print(prime_numbers)