# -*- coding: utf-8 -*-
"""Programming_Assignment1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12K4877lIlaD47dkBtE7PJGFgFIdvcuTH

Write a Python program to print &quot;Hello Python&quot;?
"""

print('Hello Python')

#Write a Python program to do arithmetical operations addition and division.?

Num1 = int(input('Enter the first number '))
Num2 = int(input('Enter the second number'))
Operation = input('Do you want to do addition or division? for addition type add and for division type divide ')

if Operation == 'add':
  Result = Num1 + Num2
  print(Result)

elif Operation =='divide':
  Result = Num1/Num2
  print(Result)

else: print('Enter the valid operation')

#Write a Python program to find the area of a triangle?
Num1 = int(input('Enter length '))
Num2 = int(input('Enter height'))

print(0.5*Num1*Num2)

#Write a Python program to swap two variables?

A= 5
B = 7

A = A+B
B = A-B 
A = A-B

print(A,B)
#print(B)

#Write a Python program to generate a random number?
import random
random_number = random.random()

print(random_number)